<?php include_once('templates/header.php') ?>
<img src="images\skinpeeling.jpg" alt="" width="500" style="margin: 20px;">
<p>
    What is the treatment? Skin Peeling Treatment is also known as Desquamation Treatment. How is the treatment done? Peeling skin could be a result of various causes like exposure to sunlight rich in ultra-violet rays that is detrimental to the skin, use
    of medications containing retinoids and benzoyl peroxide which are used to treat acnes and other skin problems, pre-existing skin diseases like eczema, psoriasis and seborrheic dermatitis and extreme dryness. Skin peeling treatment exfoliates the
    skin by removing the dead cells and making way for new skin cells to develop. There are various methods of skin peeling treatment like Yellow Peel, Agripeel, Pumpkin Peel, Peel Booster, AHA Peel, and Chemical Peel. Chemical Peel again comes in various
    forms where acids are used to treat different kinds of skin disorders. The Chemical Peel treatment includes Salicylic Acid Peel, Glycolic Acid Peel, Trichloroacetic Acid Peel, Phenol Peel, and Fruit Acid Peel. Chemical skin peeling is the best way
    to treat acnes, acne scars, freckles, rough and patchy skin. The treatment should be followed by certain measures. For example, one should avoid anti-acne creams 2-3 days prior and post to treatment. Sun-screen lotion should be applied after treatment
    and the individual should refrain from washing his/her face for 24 hours after the treatment. If rashes or redness is observed cold compress should be applied on the affected area. Who is eligible for the treatment? (When is the treatment done?) Skin
    Peeling Treatment comes in various formats. Yellow Peel is applied to enhance the oxygen supply to the skin and it makes the skin firm. An Agripeel reduces the number of swelling in the skin. An AHA Peel works best to cure dry skin as it improves
    the skin’s capacity to retain moisture. Pumpkin is a natural product rich in Vitamin A and a Pumpkin Peel rejuvenates damaged skin. Chemical Skin Peeling treatment is performed after the doctor has cleaned the skin thoroughly. Then the doctor observes
    whether the skin is reacting adversely to the chemical. If nothing happens, the doctor goes head with the procedure. Chemical Peel includes Salicylic Acid Peel which helps to open the pores and destroys the acnes that cause the bacteria to progress
    and make further damages. Trichloroacetic Acid Peel is performed to cure severe skin damage. This peel contains very high concentration of acid. Therefore it cannot be left on the skin for more than a minute or two. It works well with conditions such
    as melasma (skin discoloration), scars caused by the sun, severe acnes and pigmentation. Phenol peel is the most potent form of chemical skin peeling. It is usually followed by anesthesia. The procedure is followed by a long recovery time. However,
    this peel reaches the depth of the skin, thereby making it a very productive form of skin peeling treatment. Fruit Acid Peel uses various acids like Citric Acid, Lactic Acid, Malic Acid etc. It is the best treatment for skin lightening. Who is not
    eligible for the treatment? Anyone who is suffering from skin problems like acne, peeling skin, blemishes, pigmentation, sin discoloration, scars etc can opt for skin peeling treatment. Are there any side effects? A person with pigments on the darker
    side should especially be cautious about going ahead with a skin peeling program. It is because the area of the skin which will be regenerated will tend to be lighter than the rest of the skin, rendering the entire feature an odd appearance. What
    are the post-treatment guidelines? Skin Peeling is mostly a potent form of skin healing treatment. However, a patient should make the consulting dermatologist with his/her medical history because this treatment can cause infections like herpes or
    cold sores (pus-filled blisters) to recur in people who have a record of such ailments. Other than that this treatment can also cause blemishes, abnormal pigmentation and short-lived or long-lived discoloration. How long does it take to recover? Skin
    Peeling treatments that are performed using natural products are harmless and need not require any aftercare. However chemical skin peeling treatment shall be followed by certain measures such as a person should not use acne creams 2-3 days before
    and after the treatment. Sun exposure should be completely avoided for 2-3 days and if necessity calls then the person should SPF creams. Face should not be washed with water for 24 hours post treatment. It should be cleaned with a mild cleanser and
    non-moisturizing creams should be used. A person should refrain from swimming for 2 3 days after treatment. Make-up should also be avoided. If the skin develops red patches or rashes then they should be treated with cold compress. What is the price
    of the treatment in India? Depending on the condition of the skin the recovery time varies from person to person. But generally it takes 7-14 days to recover after undergoing a skin peeling treatment. The treatment itself takes mostly 15 minutes or
    half an hour. It does not need any hospitalization. In some cases the patient is etherized. However once the treatment is done he/she is discharged. Are the results of the treatment permanent? The price of a skin peeling treatmet can be anywhere between
    Rs 1500 and Rs 3000 per session. What are the alternatives to the treatment? The treatment is not permanent and it needs to be repeated after six months or in some cases even lesser than that, that is after 2 and a half months depending on the person’s
    skin condition.
</p>
<?php include_once('templates/footer.php') ?>